/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs/$programId/index'
import { Route as ProgramsProgramIdTasksRouteImport } from './routes/programs/$programId/tasks'
import { Route as ProgramsProgramIdPrecheckRouteImport } from './routes/programs/$programId/precheck'

const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scheduling.lazy').then((d) => d.Route))
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/insights.lazy').then((d) => d.Route))
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/discovery.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/programs/$programId/',
  path: '/programs/$programId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/programs/$programId/index.lazy').then((d) => d.Route),
)
const ProgramsProgramIdTasksRoute = ProgramsProgramIdTasksRouteImport.update({
  id: '/programs/$programId/tasks',
  path: '/programs/$programId/tasks',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/programs/$programId/tasks.lazy').then((d) => d.Route),
)
const ProgramsProgramIdPrecheckRoute =
  ProgramsProgramIdPrecheckRouteImport.update({
    id: '/programs/$programId/precheck',
    path: '/programs/$programId/precheck',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/programs/$programId/precheck.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/scheduling': typeof SchedulingRoute
  '/programs/$programId/precheck': typeof ProgramsProgramIdPrecheckRoute
  '/programs/$programId/tasks': typeof ProgramsProgramIdTasksRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/scheduling': typeof SchedulingRoute
  '/programs/$programId/precheck': typeof ProgramsProgramIdPrecheckRoute
  '/programs/$programId/tasks': typeof ProgramsProgramIdTasksRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/scheduling': typeof SchedulingRoute
  '/programs/$programId/precheck': typeof ProgramsProgramIdPrecheckRoute
  '/programs/$programId/tasks': typeof ProgramsProgramIdTasksRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discovery'
    | '/insights'
    | '/scheduling'
    | '/programs/$programId/precheck'
    | '/programs/$programId/tasks'
    | '/programs/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery'
    | '/insights'
    | '/scheduling'
    | '/programs/$programId/precheck'
    | '/programs/$programId/tasks'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/discovery'
    | '/insights'
    | '/scheduling'
    | '/programs/$programId/precheck'
    | '/programs/$programId/tasks'
    | '/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryRoute: typeof DiscoveryRoute
  InsightsRoute: typeof InsightsRoute
  SchedulingRoute: typeof SchedulingRoute
  ProgramsProgramIdPrecheckRoute: typeof ProgramsProgramIdPrecheckRoute
  ProgramsProgramIdTasksRoute: typeof ProgramsProgramIdTasksRoute
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/tasks': {
      id: '/programs/$programId/tasks'
      path: '/programs/$programId/tasks'
      fullPath: '/programs/$programId/tasks'
      preLoaderRoute: typeof ProgramsProgramIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/precheck': {
      id: '/programs/$programId/precheck'
      path: '/programs/$programId/precheck'
      fullPath: '/programs/$programId/precheck'
      preLoaderRoute: typeof ProgramsProgramIdPrecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryRoute: DiscoveryRoute,
  InsightsRoute: InsightsRoute,
  SchedulingRoute: SchedulingRoute,
  ProgramsProgramIdPrecheckRoute: ProgramsProgramIdPrecheckRoute,
  ProgramsProgramIdTasksRoute: ProgramsProgramIdTasksRoute,
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
