/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as BrilliantRouteRouteImport } from './routes/brilliant/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsV2IndexRouteImport } from './routes/programs-v2/index'
import { Route as BrilliantIndexRouteImport } from './routes/brilliant/index'
import { Route as ModesScrollyRouteImport } from './routes/modes/scrolly'
import { Route as ModesNotionRouteImport } from './routes/modes/notion'
import { Route as ModesM3RouteImport } from './routes/modes/m3'
import { Route as ModesEditorialRouteImport } from './routes/modes/editorial'
import { Route as ModesBentoRouteImport } from './routes/modes/bento'
import { Route as BrilliantJourneyRouteImport } from './routes/brilliant/journey'
import { Route as BrilliantFocusRouteImport } from './routes/brilliant/focus'
import { Route as BrilliantDashboardRouteImport } from './routes/brilliant/dashboard'
import { Route as BrilliantBentoRouteImport } from './routes/brilliant/bento'
import { Route as BrilliantAnalyticsRouteImport } from './routes/brilliant/analytics'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs/$programId/index'
import { Route as BrilliantProgrammesIndexRouteImport } from './routes/brilliant/programmes/index'
import { Route as ProgramsProgramIdTasksRouteImport } from './routes/programs/$programId/tasks'
import { Route as ProgramsProgramIdPrecheckRouteImport } from './routes/programs/$programId/precheck'
import { Route as BrilliantProgrammesTimelineRouteImport } from './routes/brilliant/programmes/timeline'
import { Route as BrilliantProgrammesTableRouteImport } from './routes/brilliant/programmes/table'
import { Route as BrilliantProgrammesSkillmapRouteImport } from './routes/brilliant/programmes/skillmap'
import { Route as BrilliantProgrammesMosaicRouteImport } from './routes/brilliant/programmes/mosaic'
import { Route as BrilliantProgrammesMagazineRouteImport } from './routes/brilliant/programmes/magazine'
import { Route as BrilliantProgrammesKanbanRouteImport } from './routes/brilliant/programmes/kanban'
import { Route as BrilliantProgrammesDetailRouteImport } from './routes/brilliant/programmes/detail'
import { Route as BrilliantProgrammesChecklistRouteImport } from './routes/brilliant/programmes/checklist'

const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/discovery.lazy').then((d) => d.Route))
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const BrilliantRouteRoute = BrilliantRouteRouteImport.update({
  id: '/brilliant',
  path: '/brilliant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsV2IndexRoute = ProgramsV2IndexRouteImport.update({
  id: '/programs-v2/',
  path: '/programs-v2/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrilliantIndexRoute = BrilliantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrilliantRouteRoute,
} as any)
const ModesScrollyRoute = ModesScrollyRouteImport.update({
  id: '/modes/scrolly',
  path: '/modes/scrolly',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesNotionRoute = ModesNotionRouteImport.update({
  id: '/modes/notion',
  path: '/modes/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesM3Route = ModesM3RouteImport.update({
  id: '/modes/m3',
  path: '/modes/m3',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesEditorialRoute = ModesEditorialRouteImport.update({
  id: '/modes/editorial',
  path: '/modes/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesBentoRoute = ModesBentoRouteImport.update({
  id: '/modes/bento',
  path: '/modes/bento',
  getParentRoute: () => rootRouteImport,
} as any)
const BrilliantJourneyRoute = BrilliantJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => BrilliantRouteRoute,
} as any)
const BrilliantFocusRoute = BrilliantFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => BrilliantRouteRoute,
} as any)
const BrilliantDashboardRoute = BrilliantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BrilliantRouteRoute,
} as any)
const BrilliantBentoRoute = BrilliantBentoRouteImport.update({
  id: '/bento',
  path: '/bento',
  getParentRoute: () => BrilliantRouteRoute,
} as any)
const BrilliantAnalyticsRoute = BrilliantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BrilliantRouteRoute,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/programs/$programId/',
  path: '/programs/$programId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/programs/$programId/index.lazy').then((d) => d.Route),
)
const BrilliantProgrammesIndexRoute =
  BrilliantProgrammesIndexRouteImport.update({
    id: '/programmes/',
    path: '/programmes/',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const ProgramsProgramIdTasksRoute = ProgramsProgramIdTasksRouteImport.update({
  id: '/programs/$programId/tasks',
  path: '/programs/$programId/tasks',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/programs/$programId/tasks.lazy').then((d) => d.Route),
)
const ProgramsProgramIdPrecheckRoute =
  ProgramsProgramIdPrecheckRouteImport.update({
    id: '/programs/$programId/precheck',
    path: '/programs/$programId/precheck',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/programs/$programId/precheck.lazy').then((d) => d.Route),
  )
const BrilliantProgrammesTimelineRoute =
  BrilliantProgrammesTimelineRouteImport.update({
    id: '/programmes/timeline',
    path: '/programmes/timeline',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesTableRoute =
  BrilliantProgrammesTableRouteImport.update({
    id: '/programmes/table',
    path: '/programmes/table',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesSkillmapRoute =
  BrilliantProgrammesSkillmapRouteImport.update({
    id: '/programmes/skillmap',
    path: '/programmes/skillmap',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesMosaicRoute =
  BrilliantProgrammesMosaicRouteImport.update({
    id: '/programmes/mosaic',
    path: '/programmes/mosaic',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesMagazineRoute =
  BrilliantProgrammesMagazineRouteImport.update({
    id: '/programmes/magazine',
    path: '/programmes/magazine',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesKanbanRoute =
  BrilliantProgrammesKanbanRouteImport.update({
    id: '/programmes/kanban',
    path: '/programmes/kanban',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesDetailRoute =
  BrilliantProgrammesDetailRouteImport.update({
    id: '/programmes/detail',
    path: '/programmes/detail',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)
const BrilliantProgrammesChecklistRoute =
  BrilliantProgrammesChecklistRouteImport.update({
    id: '/programmes/checklist',
    path: '/programmes/checklist',
    getParentRoute: () => BrilliantRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brilliant': typeof BrilliantRouteRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/scheduling': typeof SchedulingRoute
  '/brilliant/analytics': typeof BrilliantAnalyticsRoute
  '/brilliant/bento': typeof BrilliantBentoRoute
  '/brilliant/dashboard': typeof BrilliantDashboardRoute
  '/brilliant/focus': typeof BrilliantFocusRoute
  '/brilliant/journey': typeof BrilliantJourneyRoute
  '/modes/bento': typeof ModesBentoRoute
  '/modes/editorial': typeof ModesEditorialRoute
  '/modes/m3': typeof ModesM3Route
  '/modes/notion': typeof ModesNotionRoute
  '/modes/scrolly': typeof ModesScrollyRoute
  '/brilliant/': typeof BrilliantIndexRoute
  '/programs-v2/': typeof ProgramsV2IndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/brilliant/programmes/checklist': typeof BrilliantProgrammesChecklistRoute
  '/brilliant/programmes/detail': typeof BrilliantProgrammesDetailRoute
  '/brilliant/programmes/kanban': typeof BrilliantProgrammesKanbanRoute
  '/brilliant/programmes/magazine': typeof BrilliantProgrammesMagazineRoute
  '/brilliant/programmes/mosaic': typeof BrilliantProgrammesMosaicRoute
  '/brilliant/programmes/skillmap': typeof BrilliantProgrammesSkillmapRoute
  '/brilliant/programmes/table': typeof BrilliantProgrammesTableRoute
  '/brilliant/programmes/timeline': typeof BrilliantProgrammesTimelineRoute
  '/programs/$programId/precheck': typeof ProgramsProgramIdPrecheckRoute
  '/programs/$programId/tasks': typeof ProgramsProgramIdTasksRoute
  '/brilliant/programmes/': typeof BrilliantProgrammesIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/scheduling': typeof SchedulingRoute
  '/brilliant/analytics': typeof BrilliantAnalyticsRoute
  '/brilliant/bento': typeof BrilliantBentoRoute
  '/brilliant/dashboard': typeof BrilliantDashboardRoute
  '/brilliant/focus': typeof BrilliantFocusRoute
  '/brilliant/journey': typeof BrilliantJourneyRoute
  '/modes/bento': typeof ModesBentoRoute
  '/modes/editorial': typeof ModesEditorialRoute
  '/modes/m3': typeof ModesM3Route
  '/modes/notion': typeof ModesNotionRoute
  '/modes/scrolly': typeof ModesScrollyRoute
  '/brilliant': typeof BrilliantIndexRoute
  '/programs-v2': typeof ProgramsV2IndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/brilliant/programmes/checklist': typeof BrilliantProgrammesChecklistRoute
  '/brilliant/programmes/detail': typeof BrilliantProgrammesDetailRoute
  '/brilliant/programmes/kanban': typeof BrilliantProgrammesKanbanRoute
  '/brilliant/programmes/magazine': typeof BrilliantProgrammesMagazineRoute
  '/brilliant/programmes/mosaic': typeof BrilliantProgrammesMosaicRoute
  '/brilliant/programmes/skillmap': typeof BrilliantProgrammesSkillmapRoute
  '/brilliant/programmes/table': typeof BrilliantProgrammesTableRoute
  '/brilliant/programmes/timeline': typeof BrilliantProgrammesTimelineRoute
  '/programs/$programId/precheck': typeof ProgramsProgramIdPrecheckRoute
  '/programs/$programId/tasks': typeof ProgramsProgramIdTasksRoute
  '/brilliant/programmes': typeof BrilliantProgrammesIndexRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brilliant': typeof BrilliantRouteRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/scheduling': typeof SchedulingRoute
  '/brilliant/analytics': typeof BrilliantAnalyticsRoute
  '/brilliant/bento': typeof BrilliantBentoRoute
  '/brilliant/dashboard': typeof BrilliantDashboardRoute
  '/brilliant/focus': typeof BrilliantFocusRoute
  '/brilliant/journey': typeof BrilliantJourneyRoute
  '/modes/bento': typeof ModesBentoRoute
  '/modes/editorial': typeof ModesEditorialRoute
  '/modes/m3': typeof ModesM3Route
  '/modes/notion': typeof ModesNotionRoute
  '/modes/scrolly': typeof ModesScrollyRoute
  '/brilliant/': typeof BrilliantIndexRoute
  '/programs-v2/': typeof ProgramsV2IndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/brilliant/programmes/checklist': typeof BrilliantProgrammesChecklistRoute
  '/brilliant/programmes/detail': typeof BrilliantProgrammesDetailRoute
  '/brilliant/programmes/kanban': typeof BrilliantProgrammesKanbanRoute
  '/brilliant/programmes/magazine': typeof BrilliantProgrammesMagazineRoute
  '/brilliant/programmes/mosaic': typeof BrilliantProgrammesMosaicRoute
  '/brilliant/programmes/skillmap': typeof BrilliantProgrammesSkillmapRoute
  '/brilliant/programmes/table': typeof BrilliantProgrammesTableRoute
  '/brilliant/programmes/timeline': typeof BrilliantProgrammesTimelineRoute
  '/programs/$programId/precheck': typeof ProgramsProgramIdPrecheckRoute
  '/programs/$programId/tasks': typeof ProgramsProgramIdTasksRoute
  '/brilliant/programmes/': typeof BrilliantProgrammesIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brilliant'
    | '/development'
    | '/discovery'
    | '/insights'
    | '/scheduling'
    | '/brilliant/analytics'
    | '/brilliant/bento'
    | '/brilliant/dashboard'
    | '/brilliant/focus'
    | '/brilliant/journey'
    | '/modes/bento'
    | '/modes/editorial'
    | '/modes/m3'
    | '/modes/notion'
    | '/modes/scrolly'
    | '/brilliant/'
    | '/programs-v2/'
    | '/programs/'
    | '/brilliant/programmes/checklist'
    | '/brilliant/programmes/detail'
    | '/brilliant/programmes/kanban'
    | '/brilliant/programmes/magazine'
    | '/brilliant/programmes/mosaic'
    | '/brilliant/programmes/skillmap'
    | '/brilliant/programmes/table'
    | '/brilliant/programmes/timeline'
    | '/programs/$programId/precheck'
    | '/programs/$programId/tasks'
    | '/brilliant/programmes/'
    | '/programs/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development'
    | '/discovery'
    | '/insights'
    | '/scheduling'
    | '/brilliant/analytics'
    | '/brilliant/bento'
    | '/brilliant/dashboard'
    | '/brilliant/focus'
    | '/brilliant/journey'
    | '/modes/bento'
    | '/modes/editorial'
    | '/modes/m3'
    | '/modes/notion'
    | '/modes/scrolly'
    | '/brilliant'
    | '/programs-v2'
    | '/programs'
    | '/brilliant/programmes/checklist'
    | '/brilliant/programmes/detail'
    | '/brilliant/programmes/kanban'
    | '/brilliant/programmes/magazine'
    | '/brilliant/programmes/mosaic'
    | '/brilliant/programmes/skillmap'
    | '/brilliant/programmes/table'
    | '/brilliant/programmes/timeline'
    | '/programs/$programId/precheck'
    | '/programs/$programId/tasks'
    | '/brilliant/programmes'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/brilliant'
    | '/development'
    | '/discovery'
    | '/insights'
    | '/scheduling'
    | '/brilliant/analytics'
    | '/brilliant/bento'
    | '/brilliant/dashboard'
    | '/brilliant/focus'
    | '/brilliant/journey'
    | '/modes/bento'
    | '/modes/editorial'
    | '/modes/m3'
    | '/modes/notion'
    | '/modes/scrolly'
    | '/brilliant/'
    | '/programs-v2/'
    | '/programs/'
    | '/brilliant/programmes/checklist'
    | '/brilliant/programmes/detail'
    | '/brilliant/programmes/kanban'
    | '/brilliant/programmes/magazine'
    | '/brilliant/programmes/mosaic'
    | '/brilliant/programmes/skillmap'
    | '/brilliant/programmes/table'
    | '/brilliant/programmes/timeline'
    | '/programs/$programId/precheck'
    | '/programs/$programId/tasks'
    | '/brilliant/programmes/'
    | '/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrilliantRouteRoute: typeof BrilliantRouteRouteWithChildren
  DevelopmentRoute: typeof DevelopmentRoute
  DiscoveryRoute: typeof DiscoveryRoute
  InsightsRoute: typeof InsightsRoute
  SchedulingRoute: typeof SchedulingRoute
  ModesBentoRoute: typeof ModesBentoRoute
  ModesEditorialRoute: typeof ModesEditorialRoute
  ModesM3Route: typeof ModesM3Route
  ModesNotionRoute: typeof ModesNotionRoute
  ModesScrollyRoute: typeof ModesScrollyRoute
  ProgramsV2IndexRoute: typeof ProgramsV2IndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ProgramsProgramIdPrecheckRoute: typeof ProgramsProgramIdPrecheckRoute
  ProgramsProgramIdTasksRoute: typeof ProgramsProgramIdTasksRoute
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilliant': {
      id: '/brilliant'
      path: '/brilliant'
      fullPath: '/brilliant'
      preLoaderRoute: typeof BrilliantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs-v2/': {
      id: '/programs-v2/'
      path: '/programs-v2'
      fullPath: '/programs-v2/'
      preLoaderRoute: typeof ProgramsV2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilliant/': {
      id: '/brilliant/'
      path: '/'
      fullPath: '/brilliant/'
      preLoaderRoute: typeof BrilliantIndexRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/modes/scrolly': {
      id: '/modes/scrolly'
      path: '/modes/scrolly'
      fullPath: '/modes/scrolly'
      preLoaderRoute: typeof ModesScrollyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/notion': {
      id: '/modes/notion'
      path: '/modes/notion'
      fullPath: '/modes/notion'
      preLoaderRoute: typeof ModesNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/m3': {
      id: '/modes/m3'
      path: '/modes/m3'
      fullPath: '/modes/m3'
      preLoaderRoute: typeof ModesM3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/editorial': {
      id: '/modes/editorial'
      path: '/modes/editorial'
      fullPath: '/modes/editorial'
      preLoaderRoute: typeof ModesEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/bento': {
      id: '/modes/bento'
      path: '/modes/bento'
      fullPath: '/modes/bento'
      preLoaderRoute: typeof ModesBentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilliant/journey': {
      id: '/brilliant/journey'
      path: '/journey'
      fullPath: '/brilliant/journey'
      preLoaderRoute: typeof BrilliantJourneyRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/focus': {
      id: '/brilliant/focus'
      path: '/focus'
      fullPath: '/brilliant/focus'
      preLoaderRoute: typeof BrilliantFocusRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/dashboard': {
      id: '/brilliant/dashboard'
      path: '/dashboard'
      fullPath: '/brilliant/dashboard'
      preLoaderRoute: typeof BrilliantDashboardRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/bento': {
      id: '/brilliant/bento'
      path: '/bento'
      fullPath: '/brilliant/bento'
      preLoaderRoute: typeof BrilliantBentoRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/analytics': {
      id: '/brilliant/analytics'
      path: '/analytics'
      fullPath: '/brilliant/analytics'
      preLoaderRoute: typeof BrilliantAnalyticsRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilliant/programmes/': {
      id: '/brilliant/programmes/'
      path: '/programmes'
      fullPath: '/brilliant/programmes/'
      preLoaderRoute: typeof BrilliantProgrammesIndexRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/programs/$programId/tasks': {
      id: '/programs/$programId/tasks'
      path: '/programs/$programId/tasks'
      fullPath: '/programs/$programId/tasks'
      preLoaderRoute: typeof ProgramsProgramIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/precheck': {
      id: '/programs/$programId/precheck'
      path: '/programs/$programId/precheck'
      fullPath: '/programs/$programId/precheck'
      preLoaderRoute: typeof ProgramsProgramIdPrecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilliant/programmes/timeline': {
      id: '/brilliant/programmes/timeline'
      path: '/programmes/timeline'
      fullPath: '/brilliant/programmes/timeline'
      preLoaderRoute: typeof BrilliantProgrammesTimelineRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/table': {
      id: '/brilliant/programmes/table'
      path: '/programmes/table'
      fullPath: '/brilliant/programmes/table'
      preLoaderRoute: typeof BrilliantProgrammesTableRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/skillmap': {
      id: '/brilliant/programmes/skillmap'
      path: '/programmes/skillmap'
      fullPath: '/brilliant/programmes/skillmap'
      preLoaderRoute: typeof BrilliantProgrammesSkillmapRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/mosaic': {
      id: '/brilliant/programmes/mosaic'
      path: '/programmes/mosaic'
      fullPath: '/brilliant/programmes/mosaic'
      preLoaderRoute: typeof BrilliantProgrammesMosaicRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/magazine': {
      id: '/brilliant/programmes/magazine'
      path: '/programmes/magazine'
      fullPath: '/brilliant/programmes/magazine'
      preLoaderRoute: typeof BrilliantProgrammesMagazineRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/kanban': {
      id: '/brilliant/programmes/kanban'
      path: '/programmes/kanban'
      fullPath: '/brilliant/programmes/kanban'
      preLoaderRoute: typeof BrilliantProgrammesKanbanRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/detail': {
      id: '/brilliant/programmes/detail'
      path: '/programmes/detail'
      fullPath: '/brilliant/programmes/detail'
      preLoaderRoute: typeof BrilliantProgrammesDetailRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
    '/brilliant/programmes/checklist': {
      id: '/brilliant/programmes/checklist'
      path: '/programmes/checklist'
      fullPath: '/brilliant/programmes/checklist'
      preLoaderRoute: typeof BrilliantProgrammesChecklistRouteImport
      parentRoute: typeof BrilliantRouteRoute
    }
  }
}

interface BrilliantRouteRouteChildren {
  BrilliantAnalyticsRoute: typeof BrilliantAnalyticsRoute
  BrilliantBentoRoute: typeof BrilliantBentoRoute
  BrilliantDashboardRoute: typeof BrilliantDashboardRoute
  BrilliantFocusRoute: typeof BrilliantFocusRoute
  BrilliantJourneyRoute: typeof BrilliantJourneyRoute
  BrilliantIndexRoute: typeof BrilliantIndexRoute
  BrilliantProgrammesChecklistRoute: typeof BrilliantProgrammesChecklistRoute
  BrilliantProgrammesDetailRoute: typeof BrilliantProgrammesDetailRoute
  BrilliantProgrammesKanbanRoute: typeof BrilliantProgrammesKanbanRoute
  BrilliantProgrammesMagazineRoute: typeof BrilliantProgrammesMagazineRoute
  BrilliantProgrammesMosaicRoute: typeof BrilliantProgrammesMosaicRoute
  BrilliantProgrammesSkillmapRoute: typeof BrilliantProgrammesSkillmapRoute
  BrilliantProgrammesTableRoute: typeof BrilliantProgrammesTableRoute
  BrilliantProgrammesTimelineRoute: typeof BrilliantProgrammesTimelineRoute
  BrilliantProgrammesIndexRoute: typeof BrilliantProgrammesIndexRoute
}

const BrilliantRouteRouteChildren: BrilliantRouteRouteChildren = {
  BrilliantAnalyticsRoute: BrilliantAnalyticsRoute,
  BrilliantBentoRoute: BrilliantBentoRoute,
  BrilliantDashboardRoute: BrilliantDashboardRoute,
  BrilliantFocusRoute: BrilliantFocusRoute,
  BrilliantJourneyRoute: BrilliantJourneyRoute,
  BrilliantIndexRoute: BrilliantIndexRoute,
  BrilliantProgrammesChecklistRoute: BrilliantProgrammesChecklistRoute,
  BrilliantProgrammesDetailRoute: BrilliantProgrammesDetailRoute,
  BrilliantProgrammesKanbanRoute: BrilliantProgrammesKanbanRoute,
  BrilliantProgrammesMagazineRoute: BrilliantProgrammesMagazineRoute,
  BrilliantProgrammesMosaicRoute: BrilliantProgrammesMosaicRoute,
  BrilliantProgrammesSkillmapRoute: BrilliantProgrammesSkillmapRoute,
  BrilliantProgrammesTableRoute: BrilliantProgrammesTableRoute,
  BrilliantProgrammesTimelineRoute: BrilliantProgrammesTimelineRoute,
  BrilliantProgrammesIndexRoute: BrilliantProgrammesIndexRoute,
}

const BrilliantRouteRouteWithChildren = BrilliantRouteRoute._addFileChildren(
  BrilliantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrilliantRouteRoute: BrilliantRouteRouteWithChildren,
  DevelopmentRoute: DevelopmentRoute,
  DiscoveryRoute: DiscoveryRoute,
  InsightsRoute: InsightsRoute,
  SchedulingRoute: SchedulingRoute,
  ModesBentoRoute: ModesBentoRoute,
  ModesEditorialRoute: ModesEditorialRoute,
  ModesM3Route: ModesM3Route,
  ModesNotionRoute: ModesNotionRoute,
  ModesScrollyRoute: ModesScrollyRoute,
  ProgramsV2IndexRoute: ProgramsV2IndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ProgramsProgramIdPrecheckRoute: ProgramsProgramIdPrecheckRoute,
  ProgramsProgramIdTasksRoute: ProgramsProgramIdTasksRoute,
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
